export const REFRESH_TOKEN_REPOSITORY = Symbol('REFRESH_TOKEN_REPOSITORY');

export const USER_CACHE_SERVICE = Symbol('USER_CACHE_SERVICE');

export const PERMISSION_CACHE_SERVICE = Symbol('PERMISSION_CACHE_SERVICE');

export const AUTH_JWT_SERVICE = Symbol('AUTH_JWT_SERVICE');

export const TOKEN_CACHE_SERVICE = Symbol('TOKEN_CACHE_SERVICE');

export const RESET_PASSWORD_TOKEN_CACHE_SERVICE = Symbol('RESET_PASSWORD_TOKEN_CACHE_SERVICE');
